### ISSUE TITLE
Visibility change

### ISSUE THREAD

**Issue by sanderdekroon** [wp-cli/media-command#101]
Right now the method `process_regeneration()` and all other internal methods are declared private. This makes it impossible make a small change to the inner workings of a command.

For example, I want to reduce the log output of the `regenerate` command by changing some `WP_CLI::log()` calls in the `process_regeneration()` method, but this is impossible without overriding the whole `regenerate()` method (which doesn't even have visibility).

I would like to propose to:

1. Add visibility to all methods which have no visibility right now
2. Change the visibility of internal methods to protected

**Comment by danielbachhuber** [comment]
Hi @sanderdekroon,

The methods are intentionally private to allow for refactoring in the future.

WP-CLI's formally supported methods for extensibility are:

1. Chaining command execution together.
2. Using any of the methods, functions, or classes in the [documented internal API](https://make.wordpress.org/cli/handbook/internal-api/).

The command classes aren't meant to be directly extended. You're welcome to copy the entirety of the class into your own custom command, and make whatever modifications you'd like.
