### ISSUE TITLE
Fix Travis CI caching

### ISSUE THREAD

**Issue by ntwb** [wp-cli/media-command#11]
Via @gitlost in #7:
> "(Just on the current ".travis.yml" I think the cache syntax https://github.com/wp-cli/media-command/blob/master/.travis.yml#L16 for caching "$HOME/.composer/.cache" needs to be in a "directories" list like https://github.com/gitlost/media-command/blob/imagick/.travis.yml#L16)."

@gitlost I don't think this is correct for either repo:
• https://travis-ci.org/wp-cli/media-command/jobs/222084435
• https://travis-ci.org/gitlost/media-command/jobs/222084435

Neither of the above jobs have `Setting up build cache` or `store build cache` sections

You can see both these sections in:
• https://travis-ci.org/paulgibbs/behat-wordpress-extension/jobs/224696788

Do each of the respective repos have Travis CI cache info here to view or do you see an error?
• https://travis-ci.org/wp-cli/media-command/caches
• https://travis-ci.org/gitlost/media-command/caches

**Comment by ntwb** [comment]
The #12 PR should fix this:
• `Setting up build cache` -> https://travis-ci.org/wp-cli/media-command/jobs/224810499#L155
• `could not download cache`  -> https://travis-ci.org/wp-cli/media-command/jobs/224810499#L165 <- This is correct as the cache didn't exist previously
• `store build cache` -> https://travis-ci.org/wp-cli/media-command/jobs/224810499#L361

**Comment by ntwb** [comment]
I just submitted PRs for all the things per the above, I think I got all the repos 😂

**Comment by ntwb** [comment]
I've also update the mustache template that generates this in https://github.com/wp-cli/scaffold-command/pull/8

**Comment by danielbachhuber** [comment]
👍 Thanks @ntwb !
