### ISSUE TITLE
skip existing and delete unregistred in WP cli ?

### ISSUE THREAD

**Issue by Mag8891** [wp-cli/media-command#111]
Hi is there a way to set up below commands with WP cli as well or is it set by default?
I couldn't find it anywhere.

-Skip regenerating existing correctly sized thumbnails (faster).
 -Delete thumbnail files for old unregistered sizes in order to free up server space. This may result in broken images in your posts and pages.

Many thanks

**Comment by Beee4life** [comment]
You mean [these commands](https://developer.wordpress.org/cli/commands/media/regenerate/) ?

I can't get the --skip-delete function to remove old images though... I am not the only one I saw who reported it... See [this topic](https://developer.wordpress.org/cli/commands/media/regenerate/).

**Comment by kkmuffme** [comment]
@Beee4life no this is something completely different
e.g. for a test environment I want to import pictures with a script, but some pictures may already exist in the db from previous test versions. In these cases I want to skip importing images that already exist.

Regeneration command is only for images that already exist.

**Comment by Beee4life** [comment]
Then your original post is incorrect. You ask if it's possible to : "Skip regenerating existing correctly sized thumbnails"
So yes, that is possible, with the `--only-missing` parameter.

I think you need to undertake 2 actions:
1 import the images
2 regenerate (with --only-missing)

**Comment by kkmuffme** [comment]
I'm not the OP, just having the 2nd issue too. But I guess I'll create a new card for my specific one

**Comment by Beee4life** [comment]
sorry my bad, overlooked it.

**Comment by dademaru** [comment]
> -Skip regenerating existing correctly sized thumbnails (faster).
> -Delete thumbnail files for old unregistered sizes in order to free up server space. This may result in broken images in your posts and pages.

These are options of **Regenerate Thumbnails** plugin.
However, the author of the plugin recommends:
> If you have command-line access to your site's server, consider using **WP-CLI** instead of this tool. It has a built-in regenerate command that works similarly to this tool but should be significantly faster since it has the advantage of being a command-line tool.

Unfortunately, **WP-CLI** doesn't have the second option.

It would be ideal if it could be added.

Meanwhile, an alternative with command line is to use the `rm` command with some RegEx to delete specific sizes.
