### ISSUE TITLE
Would like to be able to set album and artists for audio files as the GUI allows

### ISSUE THREAD

**Issue by shillshocked** [wp-cli/media-command#122]
It's something that I hate doing manually. I know I could edit the audio file itself, but I'd rather just have the metadata in wordpress so I can keep the audio file the same CRC.

**Comment by Horlaes** [comment]
Is this possible yet?

**Comment by schlessera** [comment]
This does actually work already with the generic `wp post meta pluck|patch` command.

Fetching the artist from attachment ID 20:
```
wp post meta pluck 20 _wp_attachment_metadata artist
```

Setting the artist from attachment ID 20 to "Michael Jackson":
```
wp post meta patch update 20 _wp_attachment_metadata artist "Michael Jackson"
```
