### ISSUE TITLE
How to make --skip-copy particularly useful

### ISSUE THREAD

**Issue by shillshocked** [wp-cli/media-command#123]
I'm trying to save disk space on my server, so I thought the --skip-copy function would come in handy. The problem is that the permalink is always set to:

https://site.com/wp-content/uploads/filename.ext

Which is not particularly useful since I have my files set into a year/monthly/episode folder structure. I know I can change the urls on the pages with search and replace, but how do I actually specify or change the permalinks for the Media Library itself? If can do that, then I can still access the media item in the media library, preview it, etc.

**Comment by danielbachhuber** [comment]
Sorry for the late reply here, @shillshocked.

The `--skip-copy` flag leaves the media file where it's currently located on the server, and simply registers it to the Media Library.

The corresponding URL will reflect the original location on the server.

Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
