### ISSUE TITLE
Regenerate with --image_size deletes all other sizes from postmeta

### ISSUE THREAD

**Issue by goaround** [wp-cli/media-command#130]
## Bug Report

--- ✅ If you are in the correct location now... --->

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I changed the height/width of an image size and tried to regenerate only the thumbnails for this specific size with`--image_size=medium` Here my full command:

`wp media regenerate --image_size=medium --skip-delete --only-missing`

After the regeneration, the REST API showed only `medium` under sizes. I checked the `postmeta` database table for the `_wp_attachment_metadata` and it seems like, that `_wp_attachment_metadata` now only contains the regenerated size, all other are gone:

```
 'sizes' => 
  array (
    'medium' => 
    array (
      'file' => 'Lissabon-Strassenbahnen-300x214.jpg',
      'width' => 300,
      'height' => 214,
      'mime-type' => 'image/jpeg',
    ),
  ),
```

If I run the command without `--image_size` its fine again:

`wp media regenerate --skip-delete --only-missing`

```
'sizes' => 
  array (
    'medium' => 
    array (
      'file' => 'Lissabon-Strassenbahnen-300x214.jpg',
      'width' => 300,
      'height' => 214,
      'mime-type' => 'image/jpeg',
    ),
    'thumbnail' => 
    array (
      'file' => 'Lissabon-Strassenbahnen-150x150.jpg',
      'width' => 150,
      'height' => 150,
      'mime-type' => 'image/jpeg',
    ),
    'medium_large' => 
    array (
      'file' => 'Lissabon-Strassenbahnen-768x548.jpg',
      'width' => 768,
      'height' => 548,
      'mime-type' => 'image/jpeg',
    ),
    'logo' => 
    array (
      'file' => 'Lissabon-Strassenbahnen-180x128.jpg',
      'width' => 180,
      'height' => 128,
      'mime-type' => 'image/jpeg',
    ),
  ),
```

**Describe how other contributors can replicate this bug**

1. Upload an Image
1. Change the size settings for `medium` in WordPress
1. Regenrate the thumbnails with `--image_size=medium`
1. Check postmeta table for `_wp_attachment_metadata`

**Describe what you would expect as the correct outcome**

I would expect, that all other sizes would still be in the metadata, only the specific size changed

**Let us know what environment you are running this on**

```
OS:	Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/usr/local/Cellar/php/7.4.0/bin/php
PHP version:	7.4.0
php.ini used:	/usr/local/etc/php/7.4/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/johanneskinast/Valet Sites/travel-dealz
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0
```

**Comment by turtlepod** [comment]
I get same problem.

**Comment by chesio** [comment]
I think I've stumbled upon the same problem. In my case I've noticed that [responsive images](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/) stopped working after I regenerated a particular image size. Since the other sizes are not included in meta, [wp_calculate_image_srcset](https://developer.wordpress.org/reference/functions/wp_calculate_image_srcset/) only outputs `full` and the recently regenerated image size...

**Comment by derweili** [comment]
I get the same error.
The other image sizes are still on the server as image files but removed from the post metadata.

**Comment by thomasmb** [comment]
Can confirm. Here is an example:

Start with image that already is correct. Now, if you run `wp media regenerate IMAGEID --image_size=thumbnail`, the `_wp_attachment_metadata` `sizes` array will only contain the thumbnail image size.

If you use the `--only-missing` option, it will only work if in fact you are missing that image size.

Running `wp media regenerate IMAGEID --only-missing` will restore the sizes array

**Comment by petersphilo** [comment]
i have had the same issue..
also, this issue seems to be the same thing:
https://github.com/wp-cli/media-command/issues/121

i can confirm that running the command 
`media regenerate --only-missing`
resolved all issues
Thank You..

**Comment by mjot** [comment]
I can confirm this problem.

**Comment by mklepaczewski** [comment]
Above PR #141 (hopefully) fixes the issue.

**Comment by marikunt** [comment]
I can confirm this issue too. The workaround without image_size and --only-missing does not work for me. All image sizes will be recreated on disk again with this workaround.

**Comment by manuhook** [comment]
Thanks @mklepaczewski Is it possible to merge https://github.com/wp-cli/media-command/pull/141 ?

**Comment by danielbachhuber** [comment]
I've just run into this issue too!

@schlessera Would it be possible to get this into v2.5.1?

**Comment by schlessera** [comment]
@danielbachhuber Yes, I can look into including that. The current PR is still missing tests, though.

**Comment by jdelia** [comment]
I've run into the same issue as well.

**Comment by danmillercoding** [comment]
Unbelievable. I've just got over 1 million image sizes unregistered due to this bug. Can this get fixed please????

**Comment by screenpartner** [comment]
Has anyone found a method of populating the missing meta data without running regenerate command for all images?

**Comment by FabienArr** [comment]
With success I do some tests, but i didn't fix the problem but it can help, i can't spend all my time on this bug but : 
If you go in the the function **regenerate** there is : 
![image](https://user-images.githubusercontent.com/87081538/203802297-19ac8eb2-c4c5-4230-9567-ce78b55d3df3.png)

The function **process_regeneration** take the --image_size parameter but the filter is put in the previously function.
And what i find is here : 

![image](https://user-images.githubusercontent.com/87081538/203804530-7a9c0fdf-91c4-44fb-9397-5e65b03f9abf.png)

https://developer.wordpress.org/reference/functions/wp_generate_attachment_metadata/
call https://developer.wordpress.org/reference/functions/wp_create_image_subsizes/

1. I don't what are the impact if we remove the image filter in **regenerate** ? 
2. I think it's better to test if metadata already exists, if it's the case why genarate the metadata and update them just ?

When i will get more time i could try to fix it, but if someone can look at this first ?

Regards

**Comment by FabienArr** [comment]
Hi,

Nobody to help me to try to fix this ?

Regards

**Comment by danielbachhuber** [comment]
Pulling in the diff from #141: https://gist.github.com/danielbachhuber/9ce0653b91faa5151882b149fca38d02

It doesn't seem like its tests currently pass, however...

```
$ composer behat -- --tags @daniel
> run-behat-tests '--tags' '@daniel'
..............................F----------------------

--- Failed steps:

001 Scenario: Regenerate all images default behavior                            # features/media-regenerate.feature:16
      And the wp-content/uploads/white-150-square-150x150.jpg file should exist # features/media-regenerate.feature:62
        /var/folders/6t/fzd50mwd57766jb0qdj2vl100000gn/T/wp-cli-test-run--63989629586e79.31321936/wp-content/uploads/white-150-square-150x150.jpg doesn't exist. (Exception)
```

**Comment by FabienArr** [comment]
OK thanks, when i will terminate my other project, i will try to do some modifications on this code, but could you confirm what i found please ?

Regards

**Comment by wojtekn** [comment]
@danielbachhuber  I'm going to check this one.

**Comment by wojtekn** [comment]
@danielbachhuber I've opened a PR for the failing test: https://github.com/wp-cli/media-command/pull/169

The tests from https://gist.github.com/danielbachhuber/9ce0653b91faa5151882b149fca38d02 succeed when I apply this diff on top of my PR. I will review the fix more and will add a separate PR for that.

**Comment by wojtekn** [comment]
I've created a PR (https://github.com/wp-cli/media-command/pull/170) with the fix from the linked gist and it fixes the issue - Behat tests go through, I tested it manually in stand-alone WP as well.

**Comment by danielbachhuber** [comment]
For posterity, it looks like this bug might've been introduced with WordPress 5.3 (November 2019): https://github.com/WordPress/wordpress-develop/commit/ca84ae50302e90ec90251f07e28c56f085116b16

Specifically, `wp_generate_attachment_metadata()` started calling `update_post_meta()`, which caused our failed state of incorrect data stored.

**Comment by galapogos01** [comment]
Is there a chance this has been reintroduced? I have had meta mysteriously go missing after a --only-missing --image_size. Running 2.6.0.

**Comment by chesio** [comment]
> Running 2.6.0.

Update your WP-CLI instance. Current version is 2.10, version 2.6.0 has been released more than two years ago...
