### ISSUE TITLE
Can't regenerate a custom size

### ISSUE THREAD

**Issue by alessandro-newzoo** [wp-cli/media-command#142]
Hi! :)

When I run the command `wp media regenerate 11381 --image_size=clients-slider`, I get:

```
$ wp media regenerate 11381 --image_size=clients-slider
Found 1 image to regenerate.
1/1 No "clients-slider" thumbnail regeneration needed for "amazon-01" (ID 11381).
Success: Regenerated 1 of 1 images.
```

But no `clients-slider` size is actually being generated for that image (or whatever image I try it with).
I checked both the server (the file is just not there), and the Regenerate Thumbnails screen for that image:

![image](https://user-images.githubusercontent.com/47320294/116697094-0d318c80-a9c3-11eb-9ef2-4741a269e812.png)

If I run the regeneration from the Regenerate Thumbnails screen it works, but I have thousands of images and it would take forever.

functions.php:

```
<?php

	add_theme_support( 'post-thumbnails' );

	add_image_size('half-width', 615, 350, array('left', 'top'));
	add_image_size('half-width-c', 615, 350, true);
	add_image_size('half-width-c-top', 615, 350, array('center', 'top'));
	add_image_size('resources', 415, 233, array('left', 'top'));
	add_image_size('full-hd', 1920, 1080, true);
	add_image_size('team-pic', 500, 500, true);
	add_image_size('clients-slider', 200, 100, false);

       ...
```

Please note my main goal is to just run ` wp media regenerate ` in order to create the custom size `clients-slider` for every image I have. After running it I've noticed they weren't being created, so I'm now trying with this one specific image just to simplify the troubleshooting process. 

Any clue please?
Thanks a lot!

**Comment by danielbachhuber** [comment]
Closing this issue as it seems a bit stale. 

Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
