### ISSUE TITLE
Is it possible to generate "XXX-scaled.jpg"?

### ISSUE THREAD

**Issue by hqin2013** [wp-cli/media-command#147]
Hi, All

For some reason,  the **"XXX-scaled.jpg" images are lost, the original image(XXX.jpg) still exists**. On the site's front, the product(WooCommerce) shows a red cross for image loss.

Tried 
` wp media regenerate 26083`

but get the error:

```
Found 1 image to regenerate.
Warning: Can't find "XXX" (ID 26083).
Error: No images regenerated (1 failed).
```

any suggestions? thank you very much.

**Comment by danielbachhuber** [comment]
Hi @hqin2013,

GitHub issues are for bug reports with specific reproduction steps. Feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
