### ISSUE TITLE
wp-cli phar doesn't contain the latest media command

### ISSUE THREAD

**Issue by krodyrobi** [wp-cli/media-command#15]
Currently the 1.1.0 phar (released Feb 1) doesn't contain the command with the `--image_size` parameter available.

Even though the docs contain the command the cli reports the parameter as unknown.
Since the media command was last updated on April 19, is it possible that the versions currently bundled are not the lastest?

`wp package list` provides no info into this as it is not considered a package.
`wp package install|update wp-cli/media-command` doesn't do anything, probably because it is considered to be core? 

Also the docs are out of sync:
 - doc comments include the param (also present in code) along with https://developer.wordpress.org/cli/commands/media/regenerate/
- readme, packagist do not

**Comment by gitlost** [comment]
The version with `--image_size` isn't released yet. You can update to the pre-release 1.2.0-alpha if you want using
```
wp cli update --nightly
```
If it doesn't suit, you can go back to the released 1.1.0 version with `wp cli update --stable`. For more info, see https://github.com/wp-cli/wp-cli#installing and https://make.wordpress.org/cli/handbook/installing/#updating-wp-cli

**Comment by pdobrescu** [comment]
in this case it might be a good idea to add a mention in the public documentation that this version is actually not yet available:

https://developer.wordpress.org/cli/commands/media/regenerate/

**Comment by gitlost** [comment]
Yes, we need something like php.net's `Changelog` entry at least.
