### ISSUE TITLE
How does delete works?

### ISSUE THREAD

**Issue by criting** [wp-cli/media-command#155]
1. Does the deletion of an old thumbnail when generation a new one is done after the new one is generated or before that?
2. Old thumbnail size was 415x415 and all thumbnails had 415x415 in the link which loads the actual resized cropped image of the original, but when generating the next thumbnails 615x615, the files are there, but all the thumbnails now have the links of the original full-size image, unless you regenerate the thumbnails from the admin panel? Why is that

**Comment by danielbachhuber** [comment]
Thanks for the questions, @criting !

> Does the deletion of an old thumbnail when generation a new one is done after the new one is generated or before that?

I believe the old thumbnail is deleted before the new one is created.

> Old thumbnail size was 415x415 and all thumbnails had 415x415 in the link which loads the actual resized cropped image of the original, but when generating the next thumbnails 615x615, the files are there, but all the thumbnails now have the links of the original full-size image, unless you regenerate the thumbnails from the admin panel? Why is that

I'm not quite sure what's going on here. It might be specific to your environment.
