### ISSUE TITLE
Option to override filename while importing media

### ISSUE THREAD

**Issue by sandeshjangam** [wp-cli/media-command#186]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

Import media from URL
```
wp media import https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg --title=abc --caption=caption --alt=alt
```

After import URL
```
http://test.local/wp-content/uploads/2023/11/pexels-photo-708587.jpeg
```

No option to override a file name `pexels-photo-708587.jpeg`

**Describe the solution you'd like**
We can introduce the new option `slug`
```
--slug=abcd 
```

After this change, after import URL will be
After import URL
```
http://test.local/wp-content/uploads/2023/11/abcd.jpeg
```

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @sandeshjangam !

I'm open to this. Feel free to submit a pull request, if you'd like. Here is some [guidance on our pull request best practices](https://make.wordpress.org/cli/handbook/contributions/pull-requests/).

**Comment by sandeshjangam** [comment]
@danielbachhuber Thanks. I will create a PR.

**Comment by danielbachhuber** [comment]
🔨
