### ISSUE TITLE
No thumbnail when importing PDF file using `media import`

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/media-command#195]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I tried importing same file using CLI and from the admin panel. Uploading through admin panel, thumbnail is generated but using `media import` command, thumbnail is not generated.

**Describe how other contributors can replicate this bug**

- Download http://wp-cli.org/behat-data/minimal-us-letter.pdf file
- `wp media import ~/Downloads/minimal-us-letter.pdf `
- File is imported but there is no thumbnail. (Ref: screenshot)
- Upload using admin panel then thumbnail is generated.

**Describe what you would expect as the correct outcome**

Thumbnail should be generated correctly.

**Let us know what environment you are running this on**

```
OS:     Darwin 22.6.0 Darwin Kernel Version 22.6.0: Tue Nov  7 21:48:06 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_X86_64 x86_64
Shell:  /bin/zsh
PHP binary:     /usr/local/bin/php
PHP version:    8.2.17
php.ini used:   /usr/local/etc/php/8.2/php.ini
MySQL binary:   /usr/local/mysql-8.0.36-macos14-x86_64/bin/mysql
MySQL version:  mysql  Ver 8.0.36 for macos14 on x86_64 (MySQL Community Server - GPL)
SQL modes:
WP-CLI root dir:        /Users/nilambarsharma/Code/wp-cli-dev/wp-cli
WP-CLI vendor dir:      /Users/nilambarsharma/Code/wp-cli-dev/wp-cli/vendor
WP_CLI phar path:
WP-CLI packages dir:    /Users/nilambarsharma/.wp-cli/packages/
WP-CLI cache dir:       /Users/nilambarsharma/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:  /Users/nilambarsharma/Sites/clean/wp-cli.local.yml
WP-CLI version: 2.11.0-alpha
```

**Provide additional context/Screenshots**

![Screenshot 2024-03-20 at 12 43 05 PM](https://github.com/wp-cli/media-command/assets/2098823/4b7b34b7-642d-4810-bcd0-d924215da097)

**Comment by murshed** [comment]
I have checked and got the same https://prnt.sc/cfwhP6gjD9n6

**Comment by Pathan-Amaankhan** [comment]
Please ensure [imagick](https://www.php.net/manual/en/imagick.setup.php) is installed while we import the PDF. 
It helps in generating previews for PDFs.

Please run `php -m` command to check the installed package & see if we have [imagick](https://www.php.net/manual/en/imagick.setup.php) installed. 😄 

<img width="1440" alt="Screenshot 2024-04-26 at 8 35 42 PM" src="https://github.com/wp-cli/media-command/assets/63953699/d639cc89-ab21-4cf6-9a48-4c75416c1b7e">

**Comment by ernilambar** [comment]
Looks like actually the imagick issue. I tested in another setup and it is working fine. Closing issue.
