### ISSUE TITLE
Needs tidying to WPCS

### ISSUE THREAD

**Issue by emirpprime** [wp-cli/media-command#20]
Initial tidying:  https://github.com/wp-cli/media-command/pull/19
Outstanding: function args.

**Comment by danielbachhuber** [comment]
> Outstanding: function args.

I don't think this is something we can fix, actually. Instead, we should eventually add a `phpcs.xml` that excludes the function args sniff.

Related https://github.com/wp-cli/scaffold-package-command/issues/70

**Comment by danielbachhuber** [comment]
I think where it's at is good enough for now. We can pick this up later when https://github.com/wp-cli/scaffold-package-command/issues/70 and https://github.com/wp-cli/wp-cli/issues/3924 land.
