### ISSUE TITLE
custom image sizes reported twice

### ISSUE THREAD

**Issue by vyskoczilova** [wp-cli/media-command#203]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

This is still happening https://github.com/wp-cli/media-command/issues/116 in 2.10.0 but it should be already fixed by https://github.com/wp-cli/media-command/pull/192 🤔 

**Describe how other contributors can replicate this bug**

- add custom image size
- run ` wp media image-size`

**Comment by ernilambar** [comment]
Yes, PR has been merged but there has been no `2.11` version released yet. Until then you can use nightly version of WP-CLI.

**Comment by vyskoczilova** [comment]
@ernilambar I thought it was fixed in 2.1.0, so it should be out by now; my bad!

**Comment by ernilambar** [comment]
Yah. Version `2.11` will be released soon.
