### ISSUE TITLE
Allow import of files from 'unsafe' URLs

### ISSUE THREAD

**Issue by emirpprime** [wp-cli/media-command#23]
A bit backwards - PR submitted earlier: https://github.com/wp-cli/media-command/pull/22

Currently media import uses wp_safe_remote_get which importantly denies import via local domain/IPs. This impliments a flag to allow use of wp_remote_get so that you can import from those locations. Writtent to cope with managing some private domain/LAN sites.

**Comment by danielbachhuber** [comment]
> This impliments a flag to allow use of wp_remote_get so that you can import from those locations. Writtent to cope with managing some private domain/LAN sites.

Can you share an example?

Is it possible to solve this problem with an existing filter?

**Comment by emirpprime** [comment]
I took https://github.com/wp-cli/wp-cli/issues/1310 to mean that add_filter couldn't be used in WP CLI commands but if I mis-read/interpreted that then there's the `http_request_reject_unsafe_urls` filter which would be much cleaner! 
I searched before trying so can go and test it unless there is anything different about using filters in CLI?

My example was a new intranet for a client:
Old site http://nww.domain.co.uk on serverA
New site http://nw2.domain.co.uk on serverB
Running `wp media import http://nww.domain.co.uk/path/to/image.jpg` from nw2 failed with invalid URL. I tracked it down to https://core.trac.wordpress.org/browser/tags/4.8/src/wp-includes/http.php#L547 where it fails as the IP for nww  is local (both are in fact).

**Comment by danielbachhuber** [comment]
> I took wp-cli/wp-cli#1310 to mean that add_filter couldn't be used in WP CLI commands but if I mis-read/interpreted that then there's the `http_request_reject_unsafe_urls` filter which would be much cleaner!

Yes, you can put your filter in a mu-plugin or similar, and then it will run when you use `wp media import`.

> I searched before trying so can go and test it unless there is anything different about using filters in CLI?

I think this particular need is best implemented as a standalone plugin, not something that needs to happen as an enhancement to `wp media import`.
