### ISSUE TITLE
Improve wp media command description

### ISSUE THREAD

**Issue by hearvox** [wp-cli/media-command#38]
Improve command description in:
https://github.com/wp-cli/media-command/blob/master/src/Media_Command.php
Command: wp media
Current description: Import new attachments or regenerate existing ones.

Proposed description:
Imports files as attachments and regenerates thumbnails.

**Comment by miya0001** [comment]
Can you give us a pull-request?

**Comment by danielbachhuber** [comment]
This description should also include mention of `wp media image-size`, which was recently added: https://github.com/wp-cli/media-command#wp-media-image-size

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/wp-cli/issues/4302

**Comment by hearvox** [comment]
Pull request coming, thanks.

Revised proposed description:
Imports files as attachments, regenerates thumbnails, lists registered image sizes.
