### ISSUE TITLE
Lack of type test results into PHP warnings

### ISSUE THREAD

**Issue by FlyingDR** [wp-cli/media-command#43]
Current code uses [wp_get_attachment_metadata](https://github.com/WordPress/WordPress/blob/bbb8d48086b7d10908f4fda673585ee122f2851d/wp-includes/post.php#L4970) function from Wordpress to retrieve attachment's metadata ([1](https://github.com/wp-cli/media-command/blob/993725f348781141135b831c39a73623c8f415a0/src/Media_Command.php#L530), [2](https://github.com/wp-cli/media-command/blob/993725f348781141135b831c39a73623c8f415a0/src/Media_Command.php#L558), [3](https://github.com/wp-cli/media-command/blob/993725f348781141135b831c39a73623c8f415a0/src/Media_Command.php#L737)). It silently assumes that returned value is array and makes no checks for it, but function description in Wordpress sources clearly states that returned value is `mixed`. 

In practice for SVG images returned metadata is empty string and it results into 6 warning messages per image.

It is necessary to add checks for returned information and, maybe, exclude SVG images from regeneration process.

**Comment by danielbachhuber** [comment]
👍

**Comment by gitlost** [comment]
I think this is best done in conjunction with https://github.com/wp-cli/media-command/issues/25, as some re-factoring is necessary.
