### ISSUE TITLE
QUESTION: Expanding import --skip-copy possible?

### ISSUE THREAD

**Issue by gnanet** [wp-cli/media-command#45]
In specific cases when the files are inside the wp-content folder but not in uploads, is it possible to set their URL according to their real position within wp-content instead to statically set the URL to wp-content/uploads?

My exact issue is, that i have PDF-s for WP Download Manager Pro  in wp-content/uploads/download-manager-files but to allow them to be indexed by SearchWP i need to import them into Medialibrary, which in turn needs to either copy them, or by using skip-copy i have to relocate the WPDMPro base directory to wp-content/uploads what is not desired.

**Comment by danielbachhuber** [comment]
> is it possible to set their URL according to their real position within wp-content instead to statically set the URL to wp-content/uploads?

You'd need to do this after the fact with `wp search-replace`
