### ISSUE TITLE
regenerate thumbnails for PDF-s (since WP 4.7)

### ISSUE THREAD

**Issue by gnanet** [wp-cli/media-command#46]
According to multiple sources starting with version 4.7 of Wordpress there are thumbnails generated for any new PDF that is uploaded into the Medialibrary:

- https://make.wordpress.org/core/2016/11/15/enhanced-pdf-support-4-7/
- http://www.wpbeginner.com/plugins/how-to-regenerate-pdf-thumbnails-in-wordpress/

Is it possible to incorporate this thumbnail generation functionality into the regenerate command?

**Comment by danielbachhuber** [comment]
Hi @gnanet,

This was implemented in https://github.com/wp-cli/wp-cli/issues/3751

**Comment by gnanet** [comment]
Sorry to reopen, if the functionality is already there, then i need to debug the concrete issue somehow, but with --debug i did not get any extra information:

> wp --debug media regenerate 1038
> Debug (bootstrap): No readable global config found (0.283s)
> Debug (bootstrap): No project config found (0.284s)
> Debug (bootstrap): argv: /usr/local/bin/wp --debug media regenerate 1038 (0.285s)
> Debug (bootstrap): ABSPATH defined: /var/www/vhosts/THEDOMAIN/httpdocs/ (0.289s)
> Debug (bootstrap): Begin WordPress load (0.29s)
> Debug (bootstrap): wp-config.php path: /var/www/vhosts/THEDOMAIN/httpdocs/wp-config.php (0.29s)
> Debug (bootstrap): Loaded WordPress (1.422s)
> Debug (bootstrap): Running command: media regenerate (1.431s)
> Found 1 image to regenerate.
> Warning: 1/1 Couldn't regenerate thumbnails for "ACBAR (Exzenter) &#8211; Getriebe" (ID 1038).
> Error: No images regenerated.

**Comment by danielbachhuber** [comment]
Hi @gnanet,

GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. Bug reports need to be reproducible with a fresh WordPress install. If your issue only reproduces in your environment, then it's likely specific to your environment. For support options, please review http://wp-cli.org/#support

**Comment by gnanet** [comment]
I promise this is the last update, if i find any really reproducible bug i open a separate issue:

In the database i found no _wp_attachment_metadata field for the PDF in question, and manually adding a properly serialized value, based on other PDF-s did not help either. Then I used the nvola fork of [force-regenerate-thumbnails](https://github.com/rvola/force-regenerate-thumbnails)  which had no problems with the generation.

**Comment by danielbachhuber** [comment]
Can you provide steps to reproduce (including associated test data), please?

**Comment by gnanet** [comment]
Ofcourse, not later than tomorrow late afternoon, because i have 117 PDF-s to be imported. 
I will replay the process, document all steps including the relevant database content state on every step. 

But I have a bad feeling that one of the plugins (most suspect is WP Download Manager Pro) hacks itself into the upload process as described [in this stackoverflow comment](https://stackoverflow.com/a/22998769/4771006) which causing the wp_generate_attachment_metadata  to return an empty array, but not die with some error.

**Comment by grappler** [comment]
I was having the same problem. After a bit of digging I realized that `wp_generate_attachment_metadata()` is failing silently when either `wp_get_image_editor()` 
or `$editor->save( $preview_file, 'image/jpeg' );` returns an error.

I have created a patch to fix this: https://core.trac.wordpress.org/ticket/35959

**Comment by fumikito** [comment]
Hi, as @grappler clarified, even if `wp_get_image_editor()` failed, `wp_generate_attachment_metadata()` tells nothing.

https://github.com/WordPress/WordPress/blob/d564af0c7ba0806051d44437788d131efafd89c3/wp-admin/includes/image.php#L671-L701

So it's hard to find the reason.

In my case, the reason is that ImageMagick restrict PDF editing due to the GhostScript's vulnerability. With this code, I found it.

```php
$attachment_id = 100; // The PDF's ID without thumbnails.
$editor = wp_get_image_editor( get_attached_file( $attachment_id ) );
if ( is_wp_error( $editor ) ) {
    echo $editor->get_error_message();
}
```

> convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408.

You can find many solutions with this keyword ""! Changing setting of the ImageMagick will work.

I left the comment for googlers. Thanks.
