### ISSUE TITLE
Add size ratio to the output of wp media image-size

### ISSUE THREAD

**Issue by johnbillion** [wp-cli/media-command#56]
The ratio of width to height of the image size could be added to the output of `wp media image-size`. I find that the ratio often helps in debugging issues where images aren't quite the right size, and seeing which sizes have the same ratio.

Calculating the ratio is straight forward. More details here: https://github.com/crstauf/query-monitor-extend/issues/1

**Comment by danielbachhuber** [comment]
👍

**Comment by runofthemill** [comment]
Opened a PR for this - #58 

I though it made sense to output "N/A" for any registered size with a soft crop, as the ratio wouldn't necessarily apply to images generated for that size.

:)
