### ISSUE TITLE
Pull from remote

### ISSUE THREAD

**Issue by nonameolsson** [wp-cli/media-command#57]
Hi!
Great plugin!

How about being able to pull all media files from a production site? That would be awesome.

**Comment by danielbachhuber** [comment]
Hi @nonameolsson,

Could you describe how this command would work in greater detail, and the problem you're trying to solve?

**Comment by nonameolsson** [comment]
I have a production site, a staging site and a development site. I would like to be able to pull all media files from production to staging, or from production to development. I already have scripts to pull the database and do search-replace from production to development.

But I always have to copy all the media files manually. A plugin for doing that would be really nice.

**Comment by danielbachhuber** [comment]
Makes sense, thanks @nonameolsson. This concept is already tracked in https://github.com/wp-cli/ideas/issues/5
