### ISSUE TITLE
Adding media diff to media command

### ISSUE THREAD

**Issue by ChrisDean** [wp-cli/media-command#6]
Following the contrib rules by opening a ticket before issuing a a PR ;)

We've put together a few functions here: https://github.com/DigitalTactics/wp-cli-mediadiff for listing what are _likely_ to be orphan files (files on the file system in the uploads folder which don't (for whatever reason) have corresponding attachment entries - yes we know some plugins manage files here too which don't result in attachments hence the _likely_); we then have options to move these files to a trash folder for inspection/retention and/or then delete them permanently if appropriate.

We think it makes sense to have our diff command trail off of media command so wp media diff <actions> makes sense to us... but what are your thoughts? Is this something you want to include

We may have some more work to on this generally but what's currently there should be of some use already.

**Comment by danielbachhuber** [comment]
👍  To `wp media diff`

Couple of questions:

* Does it need to implement a `wp media diff delete` too, or could we keep your `wp media diff display` as `wp media diff`? For a delete function, I'd think you could pass image paths to `rm`.
* Does it make sense to handle the use case in https://github.com/wp-cli/ideas/issues/32 with this too?

**Comment by ChrisDean** [comment]
On the first point it was useful for our own purposes here (it was the point of the work originally); there are checks in place in place to stop accidental behavior and unless you use the --hard option it'll put the files to the trash folder we're creating for soft deletes and inspection. On balance I think a user of the command is more (or just) as likely overall to make an irreparable mistake to their system as a result of passing output from it to rm than by using the tool directly, but happy to hear further views on that and make changes if people would rather delete wasn't there generally.

On the second point yes I think we can mod it to do wp-cli/ideas#32 as part of this. Just so I'm clear though, the intention of that is to find missing attachment sizes, so, for example, a selective thumbnail regeneration could take place? Or have I got the wrong end of the stick there?

**Comment by danielbachhuber** [comment]
> On balance I think a user of the command is more (or just) as likely overall to make an irreparable mistake to their system as a result of passing output from it to rm than by using the tool directly, but happy to hear further views on that and make changes if people would rather delete wasn't there generally.

Rather than having a dedicated command for it, we could have an example in the `## EXAMPLES` section that shows you how to safely delete files by first moving them to the trash.

One opinion of WP-CLI is [Composability is always a good idea](https://make.wordpress.org/cli/handbook/philosophy/#composability-is-always-a-good-idea), which also means:

> A corollary of this is that commands should be orthogonal, which means that there should be no overlapping functionality between commands.

The user would be more empowered to know how to use `rm` correctly.

> Just so I'm clear though, the intention of that is to find missing attachment sizes, so, for example, a selective thumbnail regeneration could take place?

Correct: identify attachments missing specific image sizes, so you know whether you need to generate those image sizes.

**Comment by danielbachhuber** [comment]
@ChrisDean Still interested in submitting this?

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/wp-cli/ideas/issues/72
