### ISSUE TITLE
Error thrown when exif data could not be read for an image

### ISSUE THREAD

**Issue by rayrutjes** [wp-cli/media-command#60]
This line throws an exception when the exif data could not be read for an image:
https://github.com/wp-cli/media-command/blob/master/src/Media_Command.php#L719

![image](https://user-images.githubusercontent.com/5570853/34317525-1c4075f6-e7b1-11e7-8be9-9f32a8a26e83.png)

We should probably be resilient to this.

**Comment by schlessera** [comment]
@rayrutjes Just wondering: you wouldn't perhaps have a broken image that we could use (without licensing issues) to build a regression test?

**Comment by schlessera** [comment]
We might be able to produce the bug with images in here: https://github.com/ianare/exif-samples/tree/master/jpg

**Comment by schlessera** [comment]
Note:
Test images can be uploaded to https://github.com/wp-cli/wp-cli.github.com/tree/master/behat-data

**Comment by rayrutjes** [comment]
@schlessera TBH I wanted to give you the images, but i had a hard time isolating them :/ . 
I needed to re-do the full import of thousands of images in a clean environment and I didn't know what to do with it anyway (but you just shared how above).

Not sure I'll have time this week to find the images that broke. I'll add it to my todolist though.

**Comment by schlessera** [comment]
@rayrutjes Ok, thanks! As I posted above, we might have found broken example files already that are CC. So, hopefully, you don't need to bother going through everything again.

**Comment by schlessera** [comment]
I could not reproduce this bug with the images from the repository of EXIF samples I posted above.

**Comment by gitlost** [comment]
Okay reproduced the PHP warning by uploading a BMP with Imagick disabled and as the GD image editor can't handle it no sizes metadata is saved, and then regenerating with Imagick enabled.

Will do fix based on this though obviously it would be much better to have at least one of the original trigger images @rayrutjes if you get the time...

PR incoming...

**Comment by rayrutjes** [comment]
I wanted to PR the image but the other repo seems read only :)
https://we.tl/BPNOcnRlgv

My logs report this one was causing the issue.

I've been unable to re-produce, probably because if you run it several time on a failing image the error occurs only the first time.
I hope this file is not a false positive.

Here is a bit more:
![image](https://user-images.githubusercontent.com/5570853/34567807-041d69d6-f164-11e7-851b-63f21f75c606.png)

**Comment by gitlost** [comment]
Thanks very much @rayrutjes. I'm guessing it is a false positive in that a different file is generating the sizes undefined message, as the `polygon-or.jpg` file does produce sizes metadata even though the EXIF is faulty. That plus the ordering (the EXIF message should occur after the sizes message on regenerate I think) and time gap.

This makes sense to me on looking at the "wp-admin/includes/image.php" code too. If you could work out which file after `polygon-or.jpg` might have no sizes metadata that would be cool, if not cool also...

**Comment by rayrutjes** [comment]
Makes sense, in that case I will need to re-do the full import on a blank new instance.
Or maybe you have a trick to remove all existing metadata?

**Comment by gitlost** [comment]
> Or maybe you have a trick to remove all existing metadata?

Not in a good way, off the top of my head!

> I will need to re-do the full import on a blank new instance

I'm happier now with the manufactured BMP method mentioned above as a reasonable test, but if that was possible and you would be able to identify the file and you have the time then that would be great...

**Comment by rayrutjes** [comment]
> but thinking about it further, the fix is trivial so probably not worth your time doing it...
That's what I was secretly thinking but didn't want to sound like a jerk.

I'll take your offer to not spend any further time on this.

Appreciate your work on this! Thank you so much.
