### ISSUE TITLE
Skipped thumbnail regeneration

### ISSUE THREAD

**Issue by mike6209** [wp-cli/media-command#64]
Hello,

I use wp media regenerate want to re-thumbnail my featured image.

But it always skipped thumbnail regeneration.

Command-line:

> $ wp media regenerate 330575
Found 1 image to regenerate.
1/1 Skipped thumbnail regeneration for "image_201812211157F8" (ID 330575).
Success: Regenerated 0 of 1 images (1 skipped)

I use each ID will be skipped, and why?

How to fix this problem.

Thanks,
mike

**Comment by schlessera** [comment]
`wp media regenerate` will skip regeneration:
* if the media file is of an unknown format
* if the media file is an image that cannot be processed (like an SVG)
* if the media file is a PDF and the server does not provide PDF capabilities

I'm closing this, as GitHub issues are not for general support, but are meant for enhancement requests and specific, reproducible bugs. For support options, please review http://wp-cli.org/#support

**Comment by gitlost** [comment]
Related https://github.com/wp-cli/media-command/issues/63
