### ISSUE TITLE
--skip-delete option not working with regerate command

### ISSUE THREAD

**Issue by martinkrcho** [wp-cli/media-command#67]
I ran into an issue with the "--skip-delete" option of the "regenerate" command. It deletes the original thumbnails. Could you please look into this?

Thanks

**Comment by danielbachhuber** [comment]
Hi @martinkrcho,

Can you please provide more details and steps to reproduce? Feel free to [review our bug reporting guidelines](https://make.wordpress.org/cli/handbook/bug-reports/)
