### ISSUE TITLE
Hook into this command

### ISSUE THREAD

**Issue by urre** [wp-cli/media-command#75]
Hi, i'm interested in doing some sanitation on filenames when doing `wp media import`, preferably using a hook. Is that possible?

**Comment by schlessera** [comment]
GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).
