### ISSUE TITLE
Regenerate Success but no update in DB

### ISSUE THREAD

**Issue by tobotomas** [wp-cli/media-command#78]
Hi, I have problem with Regenrate thumbnails. I have message:
Found 1 image to regenerate.
1/1 Regenerated thumbnails for "miss-finallll-jpg" (ID 1316609).
Success: Regenerated 1 of 1 images

But when I check db for image sizes there are no sizes set in db, so request for image size gives me back all the time only the default uploaded size. When I try to regenerate in wp admin, then is it working well. I have 64k images, so I am not able to do it in wp-admin. If I check files, the sizes are there generated correct (miss-finallll-768x404.jpg)

**Comment by schlessera** [comment]
> But when I check db for image sizes there are no sizes set in db

Are you talking about the `_wp_attachment_metadata` in the postmeta table here?
