### ISSUE TITLE
Update Examples in Documentation

### ISSUE THREAD

**Issue by terriann** [wp-cli/media-command#80]
Some of the examples in the documentation for the `wp media` command could  be improved by removing cultural references and a couple unnecessary gendered examples. This speaks to some of the changes we’ve seen in WordPress this year, as well as being a consideration for future translators and creating a sense of inclusivity with use of intentional language, even in our documentation.

I’d like to propose reusing other examples in the documentation where possible. I'll submit a pull request to get some feedback from you all.

**Comment by schlessera** [comment]
Thanks for this change. I'm not even sure what one of these words means...

Fixed via #81!
