### ISSUE TITLE
Regenerate Image Order

### ISSUE THREAD

**Issue by turtlepod** [wp-cli/media-command#82]
I was working on a large site, 150+k images. and the images need regenerated.
I ran the script for 4-5 days, and it failed at around 80%.

I think it currently process the media entry one by one using ASC order (by IDs) ?

It would be nice to be able to switch the order.

**Comment by schlessera** [comment]
Adding a way to switch the order seems rather arbitrary to me and only solves the problem you're facing as a side-effect.

I was already thinking of accepting ranges for all the commands that take one or more IDs.

So, you could do something like `wp media regenerate 25000-` to regenerate all existing IDs of 25000 and higher, or something like `wp media regenerate 200-300` to regenerate all existing IDs between 200 and 300.

I think that would solve your particular problem (restarting after the point of failure) and would probably fulfil some other use cases as well.

**Comment by turtlepod** [comment]
That would be a great solution.

**Comment by Yurciu** [comment]
Same problem here!

**Comment by schlessera** [comment]
Closing in favor of https://github.com/wp-cli/ideas/issues/105
