### ISSUE TITLE
Import media from local machin to remote server

### ISSUE THREAD

**Issue by obiwankennedy** [wp-cli/media-command#83]
I try to post some media file from my local pc to my server.  
I configured wp-cli to use ssh to connect.
I tried to import file but I got error about the file does not exist. So It tries to find it on the server machine I guess. 
```
wp media import "/local/path/to/image.jpg" --post_id=1216 --title="Some title" --featured_image --porcelain
```

Then, I change a bit my command to add -http but it does not change anything.
```
wp media import "/local/path/to/image.jpg" --post_id=1216 --title="Some title" --featured_image --porcelain --http=http://blog.domain.org/
```

I keep getting "File does not exit error"

```
display /local/path/to/image.jpg
```
Show the picture.

Is there a way to send off file to remote server ?

(my pc and my server are both in my house, I host my blog).

**Comment by schlessera** [comment]
This cannot work as-is. If you run WP-CLI through SSH on your server, a `/<local-path>/` will be local to your server, not your desktop machine ("local" is relative to where you are running WP-CLI).

`wp media import` currently does not directly support what you want to do, so you'd have to copy the file over to the server first (using `scp` or similar).

If we'd want to support this, it would be by accepting files from STDIN. This way, you could pipe from one machine to another one. It would probably look something like the following:

```
cat "/local/path/to/image.jpg" | wp @server media import - --post_id=1216 --title="Some title" --featured_image --porcelain
```

Please note that GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

If you want to get further help with figuring out how to do the above, the easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by sovetski** [comment]
Same here, hope one day will be implemented in CLI
