### ISSUE TITLE
problems regenerating thumbnails in the other languages

### ISSUE THREAD

**Issue by 8p-design** [wp-cli/media-command#91]
Hi, We just updated and have problems regenerating thumbnails in the other languages. 

Command: wp media regenerate --only-missing --yes

Old version : 
WP-CLI: 1.5.0
WORDPRESS: WordPress 4.9.5
WPML: Version: 3.9.4

New version : 
WP-CLI: 1.5.0
WORDPRESS: WordPress 4.9.8
WPML: Version: 4.0.5

Now, the CLI Command only regenerate thumbnails in the MAIN language.

Any clue? Thanks!

**Comment by schlessera** [comment]
@8p-design This is an issue with WPML, not WP-CLI. If you just skip loading WPML it should work.

Also, GitHub issues are meant for enhancement requests and specific, reproducible bugs, not for general support questions. For support options, please review http://wp-cli.org/#support

The easiest way to get support is to join us in the #cli channel on the [Make WordPress Slack Team](https://make.wordpress.org/chat/).

**Comment by trainoasis** [comment]
@8p-design did you solve this someplace else perhaps?

**Comment by 8p-design** [comment]
@trainoasis  , 
NOT SOLVED.

We ended up with workable solution:

-only generate main language thumbnails.

on second language situation:
-use icl_object_id to pull main language object id
-then use get_the_post_thumbnail_url  to pull the main language post thumbnail url.

HTH

**Comment by trainoasis** [comment]
> icl_object_id

Thanks, at least a workaround, but `icl_object_id` is supposed to be deprecated? Is `wpml_object_id` what you meant?

**Comment by 8p-design** [comment]
Thanks @trainoasis.
Yes it is deprecated since 3.2, but does not pop any error in debug or logs. Not sure when is the EOL.

Side note: Do you happen to have any nice error reporting system that would allow us to detect this without having to delve into code comments or documentation?
