### ISSUE TITLE
Feature request: Option to generate by file-type

### ISSUE THREAD

**Issue by pixelwatt** [wp-cli/media-command#93]
It would be epic if you could only generate media for specific file-types. For example, I've got a client who's site contains a large number of PDFs. I only need to regenerate files with the filetypes "image/jpeg" and "image/png". It would make use in deployments much faster if filetypes not needing thumbnail generation were never checked.

**Comment by pixelwatt** [comment]
Nevermind, I clearly missed the github examples before adding this.

**Comment by tcbarrett** [comment]
Could you add the specific example you are referring to? I don't see it here: https://github.com/wp-cli/media-command

`wp media regenerate --image_size=my_image_size --url=https://www.mysite.com/ --yes`

Tries to resize PDFs
