### ISSUE TITLE
Add a flag to `media import files` for returning the URL instead of the attachment ID

### ISSUE THREAD

**Issue by schlessera** [wp-cli/media-command#94]
Moved from https://github.com/wp-cli/wp-cli/issues/4666 by @killown

---

hi there, could you implement a way to return the file url after import?

Example:
> wp media import test.txt --return_url 
https://mywordpress.com/test.txt

**Comment by justinmaurerdotdev** [comment]
I'm looking into this at Contributor Day.

**Comment by danielbachhuber** [comment]
🔨
